package org.citydb.ade.iur.schema;

public enum ADESequence {
    POPULATIONBYAGEAND_SEQ,
    LANDPRICEPERLANDUS_SEQ,
    NUMBEROFANNUALDIVE_SEQ,
    NUMBEROFHOUSEHOLDS_SEQ,
    BUILDINGDETAILS_SEQ,
    LARGECUSTOMERFACIL_SEQ,
    TRAFFICVOLUME_SEQ,
    LEGALGROUNDS_SEQ,
    NUMBEROFHOUSEHOL_SEQ_1
}
